In [38]:
import tensorflow as tf
from ray.rllib.offline.json_reader import JsonReader
import numpy as np
import numpy_indexed as npi
import pandas as pd
#from true_state_viewer import TrueStateTreeGraphViz, display_tree_pairs
from tqdm import trange
import os

In [4]:
def node_action(action, node):
    vec = np.zeros(3)
    if action < 2: 
        return vec
    action -= 2
    if action % 13 == node:
        #Analyse #Remove #Resotre
        vec[int(action) // 13] = 1
    return vec

In [2]:
data_path = '/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000'
input_reader = JsonReader(data_path)
num_episodes = int(200000/100)
num_data_points = num_episodes * 99
state_length = 91
num_actions = 41

nodes = np.zeros((num_data_points*13, 7))
actions = np.zeros((num_data_points*13, 6))
node_id = np.zeros((num_data_points*13, 13))
next_nodes = np.zeros((num_data_points*13, 7))
exploit = np.zeros((num_data_points*13, 13))
scan = np.zeros((num_data_points*13, 13))
privileged = np.zeros((num_data_points*13, 13))
user = np.zeros((num_data_points*13, 13))
unknown = np.zeros((num_data_points*13, 13))
no  = np.zeros((num_data_points*13, 13))

index = 0
for i in trange(int(num_episodes/2)):
    samples = input_reader.next()
    ts = 0
    for i in range(samples['dones'].shape[0]-1):
        if samples['dones'][i]:
            continue
            ts = 0
        for n in range(13):
            encoding = np.zeros(13)
            encoding[n] = 1
            node_id[index,:] = encoding
            nodes[index,:] = samples['obs'][i][int(n*7):int(n*7)+7]
            if ts > 0:
                actions[index,:] = np.concatenate([node_action(samples['actions'][i], n), node_action(samples['actions'][i-1], n)])
            else: 
                actions[index,:] = np.concatenate([node_action(samples['actions'][i], n), np.array([0,0,0])])
            next_nodes[index,:] = samples['obs'][i+1][int(n*7):int(n*7)+7]
            exploit[index,:] = samples['obs'][i][np.arange(0,91,step=7)]
            scan[index,:] = samples['obs'][i][np.arange(1,91,step=7)]
            privileged[index,:] = samples['obs'][i][np.arange(3,91,step=7)]
            user[index,:] = samples['obs'][i][np.arange(4,91,step=7)]
            unknown[index,:] = samples['obs'][i][np.arange(5,91,step=7)]
            no[index,:]  = samples['obs'][i][np.arange(6,91,step=7)]
            index += 1
            ts += 1

#os.mkdir(data_path + '/data')
np.save(data_path + '/data/nodes.npy', nodes)
np.save(data_path + '/data/actions.npy', actions)
np.save(data_path + '/data/node_id.npy', node_id)
np.save(data_path + '/data/next_nodes.npy', next_nodes)
np.save(data_path + '/data/exploit.npy', exploit)
np.save(data_path + '/data/scan.npy', scan)
np.save(data_path + '/data/privileged.npy', privileged)
np.save(data_path + '/data/user.npy', user)
np.save(data_path + '/data/unknown.npy', unknown)
np.save(data_path + '/data/no.npy', no)

NameError: name 'JsonReader' is not defined

In [42]:
data_path = '/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000'
input_reader = JsonReader(data_path)
num_episodes = int(200000/100)
num_data_points = num_episodes * 99
state_length = 91
num_actions = 41
seq_len = 10

states = np.zeros((num_data_points, seq_len, state_length))
rewards = np.zeros(num_data_points)
next_states = np.zeros((num_data_points, state_length))
nodes = np.zeros((num_data_points*13, seq_len, 7))
actions = np.zeros((num_data_points*13, seq_len, 3))
node_id = np.zeros((num_data_points*13, seq_len, 13))
next_nodes = np.zeros((num_data_points*13, 7))
exploit = np.zeros((num_data_points*13, seq_len, 13))
scan = np.zeros((num_data_points*13, seq_len, 13))
privileged = np.zeros((num_data_points*13, seq_len, 13))
user = np.zeros((num_data_points*13, seq_len, 13))
unknown = np.zeros((num_data_points*13, seq_len, 13))
no  = np.zeros((num_data_points*13, seq_len, 13))

s_index = 0
index = 0
for i in trange(int(num_episodes/2)):
    samples = input_reader.next()
    ts = 0
    for i in range(samples['dones'].shape[0]-1):
        if samples['dones'][i]:
            ts = 0
            continue
        steps = ts if ts < seq_len else seq_len-1  
        states[s_index,:steps+1,:] =  samples['obs'][i-steps:i+1,:]
        next_states[s_index,:] = samples['obs'][i+1,:]
        rewards[s_index] = samples['rewards'][i]
        s_index += 1
        for n in range(13):     
            encoding = np.zeros((steps, 13))
            encoding[:steps+1,n] = 1
            node_id[index,:steps+1,n] = 1
            nodes[index,:steps+1,:] = samples['obs'][i-steps:i+1,int(n*7):int(n*7)+7]
            actions[index,:steps+1,:] = np.array([node_action(samples['actions'][i], n) for i in range(i-steps,i+1)])
            next_nodes[index,:] = samples['obs'][i+1,int(n*7):int(n*7)+7]
            exploit[index,:steps+1,:] = samples['obs'][i-steps:i+1,np.arange(0,91,step=7)]
            scan[index,:steps+1,:] = samples['obs'][i-steps:i+1,np.arange(1,91,step=7)]
            privileged[index,:steps+1,:] = samples['obs'][i-steps:i+1,np.arange(3,91,step=7)]
            user[index,:steps+1,:] = samples['obs'][i-steps:i+1,np.arange(4,91,step=7)]
            unknown[index,:steps+1,:] = samples['obs'][i-steps:i+1,np.arange(5,91,step=7)]
            no[index,:steps+1,:]  = samples['obs'][i-steps:i+1,np.arange(6,91,step=7)]
            index += 1
        ts += 1
    
data_path = data_path + '/data_seqence_10'
os.mkdir(data_path)
np.save(data_path + '/nodes.npy', nodes)
np.save(data_path + '/actions.npy', actions)
np.save(data_path + '/node_id.npy', node_id)
np.save(data_path + '/next_nodes.npy', next_nodes)
np.save(data_path + '/exploit.npy', exploit)
np.save(data_path + '/scan.npy', scan)
np.save(data_path + '/privileged.npy', privileged)
np.save(data_path + '/user.npy', user)
np.save(data_path + '/unknown.npy', unknown)
np.save(data_path + '/no.npy', no)

2023-04-04 10:20:41,470	WARNING json_reader.py:239 -- Treating input directory as glob patterns: ['/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000/*.json', '/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000/*.zip']
100%|██████████| 1000/1000 [04:14<00:00,  3.93it/s]


FileExistsError: [Errno 17] File exists: '/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000/data_seqence_5'

In [41]:
np.save(data_path + '/states.npy', states)
np.save(data_path + '/next_states.npy', next_states)
np.save(data_path + '/rewards.npy', rewards)

In [46]:
data_path = '/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000'
input_reader = JsonReader(data_path)
num_episodes = int(200000/100)
num_data_points = num_episodes * 99
state_length = 91
num_actions = 41

true_actions = np.zeros((num_data_points, num_actions))

index = 0
for i in trange(int(num_episodes/2)):
    samples = input_reader.next()
    ts = 0
    for i in range(samples['dones'].shape[0]-1):
        if samples['dones'][i]:
            continue
            ts = 0
        true_actions[index,samples['actions'][i]] = 1
        index += 1

np.save(data_path + '/data/true_actions.npy', true_actions)

2023-04-04 21:23:05,828	WARNING json_reader.py:239 -- Treating input directory as glob patterns: ['/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000/*.json', '/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000/*.zip']
100%|██████████| 1000/1000 [00:13<00:00, 73.73it/s]


In [37]:
t = np.arange(0,30).reshape(3,10)
print(t)
t[-1,:] = np.zeros(10)
t = np.roll(t,1,axis=0)
t

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])