In [1]:
import tensorflow as tf
from ray.rllib.offline.json_reader import JsonReader
import numpy as np
import numpy_indexed as npi
import pandas as pd
#from true_state_viewer import TrueStateTreeGraphViz, display_tree_pairs
from tqdm import trange
import os

In [3]:
t = np.arange(10)
t[0:2]

array([0, 1])

In [2]:
def node_action(action, node):
    vec = np.zeros(3)
    if action < 2: 
        return vec
    action -= 2
    if action % 13 == node:
        #Analyse #Remove #Resotre
        vec[int(action) // 13] = 1
    return vec

In [ ]:
data_path = '/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000'
input_reader = JsonReader(data_path)
num_episodes = int(200000/100)
num_data_points = num_episodes * 99
state_length = 91
num_actions = 41

nodes = np.zeros((num_data_points*13, 7))
actions = np.zeros((num_data_points*13, 6))
node_id = np.zeros((num_data_points*13, 13))
next_nodes = np.zeros((num_data_points*13, 7))
exploit = np.zeros((num_data_points*13, 13))
scan = np.zeros((num_data_points*13, 13))
privileged = np.zeros((num_data_points*13, 13))
user = np.zeros((num_data_points*13, 13))
unknown = np.zeros((num_data_points*13, 13))
no  = np.zeros((num_data_points*13, 13))

index = 0
for i in trange(int(num_episodes/2)):
    samples = input_reader.next()
    ts = 0
    for i in range(samples['dones'].shape[0]-1):
        if samples['dones'][i]:
            continue
            ts = 0
        for n in range(13):
            encoding = np.zeros(13)
            encoding[n] = 1
            node_id[index,:] = encoding
            nodes[index,:] = samples['obs'][i][int(n*7):int(n*7)+7]
            if ts > 0:
                actions[index,:] = np.concatenate([node_action(samples['actions'][i], n), node_action(samples['actions'][i-1], n)])
            else: 
                actions[index,:] = np.concatenate([node_action(samples['actions'][i], n), np.array([0,0,0])])
            next_nodes[index,:] = samples['obs'][i+1][int(n*7):int(n*7)+7]
            exploit[index,:] = samples['obs'][i][np.arange(0,91,step=7)]
            scan[index,:] = samples['obs'][i][np.arange(1,91,step=7)]
            privileged[index,:] = samples['obs'][i][np.arange(3,91,step=7)]
            user[index,:] = samples['obs'][i][np.arange(4,91,step=7)]
            unknown[index,:] = samples['obs'][i][np.arange(5,91,step=7)]
            no[index,:]  = samples['obs'][i][np.arange(6,91,step=7)]
            index += 1
            ts += 1

#os.mkdir(data_path + '/data')
np.save(data_path + '/data/nodes.npy', nodes)
np.save(data_path + '/data/actions.npy', actions)
np.save(data_path + '/data/node_id.npy', node_id)
np.save(data_path + '/data/next_nodes.npy', next_nodes)
np.save(data_path + '/data/exploit.npy', exploit)
np.save(data_path + '/data/scan.npy', scan)
np.save(data_path + '/data/privileged.npy', privileged)
np.save(data_path + '/data/user.npy', user)
np.save(data_path + '/data/unknown.npy', unknown)
np.save(data_path + '/data/no.npy', no)

In [7]:
data_path = '/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000'
input_reader = JsonReader(data_path)
num_episodes = int(200000/100)
num_data_points = num_episodes * 99
state_length = 91
num_actions = 41
seq_len = 15

states = np.zeros((num_data_points, seq_len, state_length))
rewards = np.zeros(num_data_points)
next_states = np.zeros((num_data_points, state_length))
action_hist_oh = np.zeros((num_data_points, seq_len, num_actions))
nodes = np.zeros((num_data_points*13, seq_len, 7))
actions = np.zeros((num_data_points*13, seq_len, 3))
node_id = np.zeros((num_data_points*13, seq_len, 13))
next_nodes = np.zeros((num_data_points*13, 7))
exploit = np.zeros((num_data_points*13, seq_len, 13))
scan = np.zeros((num_data_points*13, seq_len, 13))
privileged = np.zeros((num_data_points*13, seq_len, 13))
user = np.zeros((num_data_points*13, seq_len, 13))
unknown = np.zeros((num_data_points*13, seq_len, 13))
no  = np.zeros((num_data_points*13, seq_len, 13))

s_index = 0
index = 0
for i in trange(int(num_episodes/2)):
    samples = input_reader.next()
    ts = 0
    for i in range(samples['dones'].shape[0]-1):
        if samples['dones'][i]:
            ts = 0
            continue
        steps = ts if ts < seq_len else seq_len-1 
        pad = seq_len-(ts+1) if ts < seq_len else 0  
        states[s_index,pad:,:] =  samples['obs'][i-steps:i+1,:]
        next_states[s_index,:] = samples['obs'][i+1,:]
        rewards[s_index] = samples['rewards'][i]
        #print(samples['actions'][i-steps:i+1])
        action_hist_oh[s_index,pad:,:] = np.eye(41)[samples['actions'][i-steps:i+1]]
        s_index += 1
        #for n in range(13):     
        #    encoding = np.zeros((steps, 13))
        #    encoding[:steps+1,n] = 1
        #    node_id[index,:steps+1,n] = 1
        #    nodes[index,:steps+1,:] = samples['obs'][i-steps:i+1,int(n*7):int(n*7)+7]
        #    actions[index,:steps+1,:] = np.array([node_action(samples['actions'][i], n) for i in range(i-steps,i+1)])
        #    next_nodes[index,:] = samples['obs'][i+1,int(n*7):int(n*7)+7]
        #    exploit[index,:steps+1,:] = samples['obs'][i-steps:i+1,np.arange(0,91,step=7)]
        #    scan[index,:steps+1,:] = samples['obs'][i-steps:i+1,np.arange(1,91,step=7)]
        #    privileged[index,:steps+1,:] = samples['obs'][i-steps:i+1,np.arange(3,91,step=7)]
        #    user[index,:steps+1,:] = samples['obs'][i-steps:i+1,np.arange(4,91,step=7)]
        #    unknown[index,:steps+1,:] = samples['obs'][i-steps:i+1,np.arange(5,91,step=7)]
        #    no[index,:steps+1,:]  = samples['obs'][i-steps:i+1,np.arange(6,91,step=7)]
        #    index += 1
        ts += 1
    
data_path = data_path + '/data_seqence_'+str(seq_len)
os.mkdir(data_path)
np.save(data_path + '/nodes.npy', nodes)
np.save(data_path + '/actions.npy', actions)
np.save(data_path + '/actions_oh.npy', action_hist_oh)
np.save(data_path + '/node_id.npy', node_id)
np.save(data_path + '/next_nodes.npy', next_nodes)
np.save(data_path + '/exploit.npy', exploit)
np.save(data_path + '/scan.npy', scan)
np.save(data_path + '/privileged.npy', privileged)
np.save(data_path + '/user.npy', user)
np.save(data_path + '/unknown.npy', unknown)
np.save(data_path + '/no.npy', no)
np.save(data_path + '/states.npy', states)
np.save(data_path + '/next_states.npy', next_states)
np.save(data_path + '/rewards.npy', rewards)

2023-04-27 09:38:19,234	WARNING json_reader.py:239 -- Treating input directory as glob patterns: ['/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000/*.json', '/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000/*.zip']
100%|██████████| 1000/1000 [00:18<00:00, 53.02it/s]


FileExistsError: [Errno 17] File exists: '/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000/data_seqence_15'

In [14]:
states[14]

array([[0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       ...,
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.]])

In [16]:
for n in range(13):
    print(np.array([node_action(samples['actions'][i], n) for i in range(i-steps,i+1)]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
for i in range(10000,10150):
    print(np.sum(actions[i]))

0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
2.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
0.0
0.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
1.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
0.0
0.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
2.0
1.0
0.0
0.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0
2.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
1.0
1.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
1.0
1.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
1.0


In [ ]:
data_path = '/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000'  + '/data_seqence_10'
a = np.load(data_path+'/actions_oh.npy')
a[1]

In [ ]:
np.save(data_path + '/states.npy', states)
np.save(data_path + '/next_states.npy', next_states)
np.save(data_path + '/rewards.npy', rewards)

In [ ]:
data_path = '/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/PPO/no_decoy_200000'
input_reader = JsonReader(data_path)
num_episodes = int(200000/100)
num_data_points = num_episodes * 99
state_length = 91
num_actions = 41

true_actions = np.zeros((num_data_points, num_actions))

index = 0
for i in trange(int(num_episodes/2)):
    samples = input_reader.next()
    ts = 0
    for i in range(samples['dones'].shape[0]-1):
        if samples['dones'][i]:
            continue
            ts = 0
        true_actions[index,samples['actions'][i]] = 1
        index += 1

np.save(data_path + '/data/true_actions.npy', true_actions)

In [ ]:
data_path = '/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/logs/APPO/no_decoy_800000'
input_reader = JsonReader(data_path)
num_episodes = int(800000/100)
num_data_points = num_episodes * 99
state_length = 91
num_actions = 41
seq_len = 20

states = np.zeros((num_data_points, seq_len, state_length))
rewards = np.zeros(num_data_points)
next_states = np.zeros((num_data_points, state_length))
action_hist_oh = np.zeros((num_data_points, seq_len, num_actions))

s_index = 0
index = 0
for i in trange(int(num_episodes/10)):
    samples = input_reader.next()
    ts = 0
    for i in range(samples['dones'].shape[0]-1):
        if samples['dones'][i]:
            ts = 0
            continue
        steps = ts if ts < seq_len else seq_len-1  
        states[s_index,:steps+1,:] =  samples['obs'][i-steps:i+1,:]
        next_states[s_index,:] = samples['obs'][i+1,:]
        rewards[s_index] = samples['rewards'][i]
        action_hist_oh[samples['actions'][i-steps:i+1]] = 1
        s_index += 1
        ts += 1
    
data_path = data_path + '/data_seqence_20'
os.mkdir(data_path)
np.save(data_path + '/actions_oh.npy', action_hist_oh)
np.save(data_path + '/states.npy', states)
np.save(data_path + '/next_states.npy', next_states)
np.save(data_path + '/rewards.npy', rewards)

In [ ]:
import numpy as np
t = np.arange(20).reshape((5,4))
t

In [ ]:
np.flip(t,axis=0)