In [10]:
!tensorboard --logdir=~/ray_results --host 0.0.0.0

Traceback (most recent call last):
  File "/home/adamprice/.local/bin/tensorboard", line 5, in <module>
    from tensorboard.main import run_main
  File "/home/adamprice/.local/lib/python3.8/site-packages/tensorboard/main.py", line 27, in <module>
    from tensorboard import default
  File "/home/adamprice/.local/lib/python3.8/site-packages/tensorboard/default.py", line 33, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "/home/adamprice/.local/lib/python3.8/site-packages/tensorboard/plugins/audio/audio_plugin.py", line 23, in <module>
    from tensorboard import plugin_util
  File "/home/adamprice/.local/lib/python3.8/site-packages/tensorboard/plugin_util.py", line 24, in <module>
    import markdown
  File "/home/adamprice/.local/lib/python3.8/site-packages/markdown/__init__.py", line 29, in <module>
    from .core import Markdown, markdown, markdownFromFile  # noqa: E402
  File "/home/adamprice/.local/lib/python3.8/site-packages/markdown/core.py", line 26, 

In [1]:
import numpy as np
inital_state = [0,1,2]
inital_state = np.repeat(inital_state, 2).reshape(-1,2).transpose()
inital_state

array([[0, 1, 2],
       [0, 1, 2]])

In [2]:
reward_to_index = np.load('/home/adamprice/u75a-Data-Efficient-Decisions/CybORG/CybORG/Notebooks/reward_to_index.npy', allow_pickle=True).item()

In [3]:
reward_to_index

{-14.100000381469727: 0,
 -14.0: 1,
 -13.100000381469727: 2,
 -13.0: 3,
 -12.100000381469727: 4,
 -12.0: 5,
 -11.100000381469727: 6,
 -11.0: 7,
 -4.099999904632568: 8,
 -4.0: 9,
 -3.0999999046325684: 10,
 -3.0: 11,
 -2.0999999046325684: 12,
 -2.0: 13,
 -1.100000023841858: 14,
 -1.0: 15,
 -0.10000000149011612: 16,
 0.0: 17}

In [18]:
state = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,4,5]]])
state.reshape(-1, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [9, 4, 5]])

In [7]:
import numpy as np
np.load('/home/adamprice/u75a-Data-Efficient-Decisions/rewards_dream_100.npy')

array([-312.4375 , -315.81125, -292.284  , -255.524  , -241.464  ,
       -223.86   , -210.831  , -202.806  , -189.495  , -184.291  ,
       -176.639  , -166.975  , -162.137  , -153.698  , -143.628  ,
       -128.1    , -113.013  , -104.659  ,  -96.593  ,  -93.298  ,
        -92.716  ,  -90.448  ,  -86.846  ,  -86.287  ,  -87.487  ,
        -87.105  ,  -86.453  ,  -86.016  ,  -85.064  ,  -82.859  ,
        -81.647  ,  -80.884  ,  -79.707  ,  -78.872  ,  -77.79   ,
        -77.763  ,  -76.443  ,  -75.608  ,  -75.464  ,  -75.03   ,
        -74.799  ,  -75.728  ,  -75.797  ,  -74.282  ,  -74.142  ,
        -74.614  ,  -73.489  ,  -73.533  ,  -73.965  ,  -75.301  ,
        -74.9    ,  -75.038  ,  -76.331  ,  -76.989  ,  -77.577  ,
        -76.686  ,  -75.422  ,  -73.963  ,  -74.38   ,  -75.78   ,
        -75.684  ,  -76.686  ,  -80.834  ,  -81.933  ,  -79.652  ,
        -76.907  ,  -76.66   ,  -75.911  ,  -74.928  ,  -76.218  ,
        -77.363  ,  -79.733  ,  -78.091  ,  -76.294  ,  -76.93